version: '3.8'

services:
  # Web interface service
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      - PORT=${PORT:-8000}
    env_file:
      - ../.env
    volumes:
      - ../data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Telegram bot service (no ports needed - connects to Telegram API)
  telegram-bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ["python", "telegram_runner.py"]
    env_file:
      - ../.env
    volumes:
      - ../data:/app/data
    restart: unless-stopped
    depends_on:
      - web
